-- AzGramma MVP schema

-- 1) Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  plan text not null default 'free' check (plan in ('free','plus','pro')),
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Monthly usage counters
create table if not exists public.usage_monthly (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month text not null, -- YYYY-MM
  requests_count int not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, month)
);

-- 3) updated_at trigger helper
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists usage_set_updated_at on public.usage_monthly;
create trigger usage_set_updated_at
before update on public.usage_monthly
for each row execute function public.set_updated_at();

-- 4) Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$ language plpgsql security definer;

-- Note: needs privileges in Supabase

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- 5) RLS
alter table public.profiles enable row level security;
alter table public.usage_monthly enable row level security;

-- Profiles: users can read their own profile
create policy "profiles_select_own" on public.profiles
for select
using (auth.uid() = id);

-- Profiles: users can update their name only
create policy "profiles_update_name" on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Usage: users can read their own usage
create policy "usage_select_own" on public.usage_monthly
for select
using (auth.uid() = user_id);
